/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f1xx.h"

// ---- Pin bookkeeping ----
// Each lane's Red/Yellow/Green LED is described as (which GPIO bank, which pin number).
// This is the register-level equivalent of the LANE1_RED_GPIO_Port/_Pin pairs
// CubeMX would have generated for us.
typedef struct {
    GPIO_TypeDef *port;
    uint8_t pin;
} PinDef;

PinDef redPins[4]    = { {GPIOA, 0}, {GPIOA, 3}, {GPIOA, 6}, {GPIOB, 1}  };
PinDef yellowPins[4] = { {GPIOA, 1}, {GPIOA, 4}, {GPIOA, 7}, {GPIOB, 10} };
PinDef greenPins[4]  = { {GPIOA, 2}, {GPIOA, 5}, {GPIOB, 0}, {GPIOB, 11} };

#define GREEN_TIME_MS  4000
#define YELLOW_TIME_MS 1500

// ---- millisecond timekeeping, built from the CPU's own SysTick timer ----
// This replaces HAL_Delay(). SysTick is a small hardware timer built into
// every ARM Cortex-M chip (not an ST peripheral, so it's fair game even
// without HAL) that can fire an interrupt at a fixed rate.
volatile uint32_t msTicks = 0;

void SysTick_Handler(void)   // this exact name overrides the placeholder in the startup file
{
    msTicks++;                // called automatically once every 1ms, once we configure it below
}

void delay_ms(uint32_t ms)
{
    uint32_t start = msTicks;
    while ((msTicks - start) < ms);   // just wait here until enough 1ms ticks have passed
}

// ---- turning one GPIO pin into a push-pull output ----
// STM32F103 doesn't have the simple MODER/OTYPER registers newer STM32s have.
// Instead, pins 0-7 of a port are configured in the CRL register, and pins
// 8-15 in CRH. Each pin gets 4 config bits: 2 for "mode" (output speed) and
// 2 for "CNF" (function: push-pull, open-drain, etc).5
// 0b0010 = MODE:10 (output, max 2MHz - plenty fast for LEDs), CNF:00 (general purpose push-pull).
void gpio_set_output(GPIO_TypeDef *port, uint8_t pin)
{
    if (pin < 8) {
        port->CRL &= ~(0xF << (4 * pin));   // clear this pin's 4 bits first
        port->CRL |=  (0x2 << (4 * pin));   // write push-pull output, 2MHz
    } else {
        uint8_t p = pin - 8;
        port->CRH &= ~(0xF << (4 * p));
        port->CRH |=  (0x2 << (4 * p));
    }
}

// ---- writing a pin high or low ----
// BSRR is a "set/reset register": writing to its lower 16 bits sets pins
// HIGH, writing to its upper 16 bits sets pins LOW. It's preferred over
// touching ODR directly because it's a single atomic write - no risk of
// accidentally disturbing other pins on the same port mid-operation.
void pin_write(PinDef p, uint8_t state)
{
    if (state)
        p.port->BSRR = (1U << p.pin);          // set HIGH
    else
        p.port->BSRR = (1U << (p.pin + 16));   // set LOW
}

void all_lanes_red(void)
{
    for (int i = 0; i < 4; i++) {
        pin_write(redPins[i], 1);
        pin_write(yellowPins[i], 0);
        pin_write(greenPins[i], 0);
    }
}

void run_lane_turn(int lane)
{
    all_lanes_red();
    pin_write(redPins[lane], 0);
    pin_write(greenPins[lane], 1);
    delay_ms(GREEN_TIME_MS);

    pin_write(greenPins[lane], 0);
    pin_write(yellowPins[lane], 1);
    delay_ms(YELLOW_TIME_MS);

    pin_write(yellowPins[lane], 0);
    pin_write(redPins[lane], 1);
}

int main(void)
{
    SystemCoreClockUpdate();                  // reads actual clock speed into SystemCoreClock
    SysTick_Config(SystemCoreClock / 1000);   // configure SysTick to fire every 1ms

    // Turn on the GPIOA and GPIOB peripheral clocks.
    // On STM32, a peripheral's registers don't respond to anything until its
    // clock is explicitly enabled here — this is a very common "why isn't my
    // pin doing anything" bug for beginners.
    RCC->APB2ENR |= RCC_APB2ENR_IOPAEN | RCC_APB2ENR_IOPBEN;

    // Configure all 12 pins as outputs
    for (int i = 0; i < 4; i++) {
        gpio_set_output(redPins[i].port, redPins[i].pin);
        gpio_set_output(yellowPins[i].port, yellowPins[i].pin);
        gpio_set_output(greenPins[i].port, greenPins[i].pin);
    }

    all_lanes_red();   // safe state at power-on

    while (1) {
        for (int lane = 0; lane < 4; lane++) {
            run_lane_turn(lane);
        }
    }
}
